[package]
name = "deskulpt_rolldown_workspace"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
description = "[FORK] Rolldown's rolldown_workspace crate."

[lib]
name = "rolldown_workspace"
doctest = false

[lints]
workspace = true
