[package]
name = "deskulpt_rolldown_tracing"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
description = "[FORK] Rolldown's rolldown_tracing crate."

[lints]
workspace = true

[lib]
name = "rolldown_tracing"
bench = false
doctest = false
test = false

[dependencies]
tracing = { workspace = true, features = ["valuable"] }
tracing-chrome = { workspace = true }
tracing-subscriber = { workspace = true, default-features = false, features = ["std"] }
