[package]
name = "deskulpt_rolldown_string_wizard"
version = "0.1.0"
description = "[FORK] Rolldown's string_wizard crate."
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "string_wizard"

[dependencies]
oxc_index = { workspace = true }
oxc_sourcemap = { workspace = true, optional = true }
rustc-hash = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
insta = { workspace = true }

[features]
default = ["sourcemap", "serde"]
serde = ["dep:serde", "oxc_index/serde"]
sourcemap = ["dep:oxc_sourcemap"]

[package.metadata.cargo-shear]
ignored = ["serde"]
