[package]
name = "ls-lint"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
deskulpt_rolldown_workspace = { workspace = true }
globset = "0.4"
heck = { workspace = true }
ignore = "0.4"
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
